### ISSUE TITLE
Internal error when trying to copy entities

### ISSUE THREAD

**Issue by celdorwow** [Grimrukh/soulstruct#25]
![soulstructeditor](https://github.com/Grimrukh/soulstruct/assets/46614084/f1a448f9-6fcb-4b7b-90df-75a77ef8ad26)
I am trying to create a project for Elden Ring but due to the error I cannot even start the application. These are steps before the app closes with an exception:

* I select a game: Elden Ring
    * it's a completely new and empty folder `Test` for a project directory
* This is followed by a message **Entities Import** _Could not find any entities in project..._
    * I choose _Yes, copy from Soulstruct_
    * It leads to the error: **Internal Error** _Fata internal error encountered (see log for full traceback):_ _[WinError 3] The system cannot find the path specified:_ `C:\\Users\\...\\AddData\\Local\\Temp\\_MEI140922\\soulstruct\\eldenring\\events\\vanilla\\entities`

At the end the app crashes with an exception (screenshot provided).

```
Traceback (most recent call last):
  File "soulstruct\__main__.py", line 241, in <module>
  File "soulstruct\__main__.py", line 235, in soulstruct_main
  File "soulstruct\base\project\window.py", line 108, in __init__
  File "soulstruct\base\project\core.py", line 113, in __init__
  File "soulstruct\base\project\core.py", line 185, in initialize_project
  File "soulstruct\eldenring\project\core.py", line 73, in import_events
  File "soulstruct\eldenring\events\create_vanilla_entities.py", line 135, in copy_vanilla_entities
  File "shutil.py", line 554, in copytree
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\...\\AppData\\Local\\Temp\\_MEI140922\\soulstruct\\eldenring\\events\\vanilla\\entities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "soulstruct\__main__.py", line 245, in <module>
RuntimeError: input(): lost sys.stdin
```

I wonder if there is something I need for the application to work. Should I get extra files besides the main executable?

EDIT. I actually can start the app if I skip importing **Entities Import** but the window looks like in the screenshot I provided. The editor missing essentially all the tabs.

![soulstructeditor](https://github.com/Grimrukh/soulstruct/assets/46614084/71d726ff-1622-42d3-9501-311bc630cfb6)

I also watched this video [How to Mod Dark Souls [Episode 1: Basics and Maps](https://www.youtube.com/watch?v=V76X6tDEK7Q). It is difficult to say what the chain of action is because the author presents different alternatives should one choose different version of Dark Souls I, Dark Souls I Remastered etc., including the Windows 10 waring about unrecognised executables. However, in none of the alternatives, does `SoulstructProjectEditor.exe` ask about **Entities Import**, which leads to the fatal error in my case. The app also does not ask about ELDEN RING game folder any more, which is odd. I don't know if this is written somewhere? In my case Elding ring is installed in different location. Honestly, I can't figure out what's happening.

**Comment by celdorwow** [comment]
If someone is trying to get help here, I believe this project is pretty much abandoned.
